import { Dialog, DialogContent, DialogTrigger } from '@/components/ui/dialog';
import { cn } from '@/lib/utils';
import type { ChatImagePayload } from '../domain/types';

interface ChatImageProps {
  image: ChatImagePayload;
  className?: string;
}

export function ChatImage({ image, className }: ChatImageProps) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <div
          className={cn(
            'relative group cursor-zoom-in overflow-hidden rounded-lg border bg-muted',
            className
          )}
        >
          <img
            src={image.url}
            alt={image.alt || 'AI generated image'}
            className="w-full h-auto object-cover transition-transform group-hover:scale-105"
            loading="lazy"
          />
          {image.generatedBy && (
            <div className="absolute bottom-2 right-2 px-2 py-1 bg-black/60 text-white text-[10px] rounded backdrop-blur-sm">
              Generated by {image.generatedBy}
            </div>
          )}
        </div>
      </DialogTrigger>
      <DialogContent className="max-w-4xl p-0 overflow-hidden bg-transparent border-none shadow-none">
        <img
          src={image.url}
          alt={image.alt || 'AI generated image'}
          className="w-full h-auto rounded-lg shadow-2xl"
        />
      </DialogContent>
    </Dialog>
  );
}
