// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soqfclgupivjcdiiwmta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcWZjbGd1cGl2amNkaWl3bXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzIxNjcsImV4cCI6MjA2MzYwODE2N30.mIhmjFm3nrc3so4GIxtRZHW9B8x525qWR9ULOW1GxaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);