name: Color Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-colors:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Run color validation
        id: color-validation
        run: |
          bun run validate:colors > validation-output.txt 2>&1 || echo "VALIDATION_FAILED=true" >> $GITHUB_ENV
          cat validation-output.txt
        continue-on-error: true
      
      - name: Check validation result
        if: env.VALIDATION_FAILED == 'true'
        run: |
          echo "❌ Color validation failed!"
          echo "Please fix hardcoded colors before merging."
          echo ""
          echo "💡 Use semantic tokens instead:"
          echo "  - success, warning, destructive, info"
          echo "  - financial-positive, financial-negative, financial-neutral"
          echo "  - pix-primary, pix-accent"
          echo ""
          echo "📖 See docs/design-specs/COLOR-SYSTEM-GUIDE.md for details"
          exit 1
      
      - name: Success message
        if: env.VALIDATION_FAILED != 'true'
        run: |
          echo "✅ Color validation passed!"
          echo "All components use semantic color tokens correctly."
      
      - name: Upload validation report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: color-validation-report
          path: validation-output.txt

